#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import h5py
import numpy as np
import pandas as pd
import torch


def _sphere_mask(shape: tuple[int, int, int], center: tuple[int, int, int], radius: float) -> np.ndarray:
    zz, yy, xx = np.indices(shape)
    dz = zz - int(center[0])
    dy = yy - int(center[1])
    dx = xx - int(center[2])
    return (dz * dz + dy * dy + dx * dx) <= float(radius) ** 2


def create_synthetic_raw(shape: tuple[int, int, int] = (32, 48, 48), seed: int = 7) -> np.ndarray:
    rng = np.random.default_rng(seed)
    raw = rng.normal(loc=0.05, scale=0.01, size=shape).astype(np.float32)

    organoids = [
        ((12, 18, 18), 6.0, 0.82),
        ((20, 31, 30), 7.0, 0.72),
    ]
    for center, radius, intensity in organoids:
        mask = _sphere_mask(shape, center, radius)
        raw[mask] = intensity + rng.normal(loc=0.0, scale=0.03, size=int(mask.sum())).astype(np.float32)

    return np.clip(raw, 0.0, 1.0).astype(np.float32)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Create synthetic demo inputs for the deepFORMA atlas builder.")
    p.add_argument("--out-dir", type=Path, default=Path("demo"), help="Directory where demo assets will be written.")
    p.add_argument("--sample-id", default="DEMO001", help="Synthetic sample identifier.")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    out_dir: Path = args.out_dir
    h5_dir = out_dir / "h5_raw"
    model_dir = out_dir / "model"
    h5_dir.mkdir(parents=True, exist_ok=True)
    model_dir.mkdir(parents=True, exist_ok=True)

    sample_id = str(args.sample_id)
    raw = create_synthetic_raw()
    h5_path = h5_dir / f"{sample_id}.h5"
    with h5py.File(h5_path, "w") as f:
        f.create_dataset("raw", data=raw, compression="gzip")
        f.attrs["description"] = "Synthetic min-max normalized MRI-like volume for demo/testing only."

    atlas = pd.DataFrame(
        [
            {
                "Raw_Data_ID": sample_id,
                "Cell_Line": "demo",
                "Timepoint_Days": 0,
                "Treatment": "synthetic",
                "Demo_Notes": "Generated by scripts/create_demo_assets.py; not biological data.",
            }
        ]
    )
    atlas_path = out_dir / "atlas_existing.xlsx"
    atlas.to_excel(atlas_path, index=False)

    checkpoint_path = model_dir / "demo_zscore_passthrough.pt"
    torch.save(
        {
            "model_type": "demo_zscore_passthrough",
            "scale": 1.0,
            "bias": 0.0,
            "description": "Demo-only checkpoint; not trained and not suitable for scientific inference.",
        },
        checkpoint_path,
    )

    print(f"Wrote synthetic H5: {h5_path}")
    print(f"Wrote atlas metadata: {atlas_path}")
    print(f"Wrote demo checkpoint: {checkpoint_path}")
    print("Next command:")
    print(
        "python scripts/build_database.py "
        f"--model-path {checkpoint_path} "
        f"--h5-raw-dir {h5_dir} "
        f"--atlas-existing {atlas_path} "
        f"--out-root {out_dir / 'output'} "
        "--tag demo "
        "--out-atlas-name FORMA_Atlas_demo.xlsx "
        "--min-volume 20"
    )


if __name__ == "__main__":
    main()
